### ISSUE TITLE
2024-05

### ISSUE THREAD

**Issue by wdssmq** [wdssmq/GesF-Note#3]
```yml
Title: 「水坑」开发 Z-BlogPHP 应用时实现自动刷新网页
Desc: 具体列举了三种实现 PHP 网站开发时自动刷新网页的方法，也并不局限于 Z-BlogPHP；
Image: null
Source: "[url=https://space.bilibili.com/44744006]沉冰浮水@bilibili[/url]"
Tags: 哔哩哔哩
Type: 视频
Url: https://www.bilibili.com/video/BV1vTMeetEEo

```

**Comment by wdssmq** [comment]
```yml
Title: 「折腾」VSCode 扩展分组管理
Desc: 使用「扩展管理器（Extension Manager）」扩展对其他扩展进行分组，实现按需批量启用或者停止；
Image: null
Source: "[url=https://space.bilibili.com/44744006]沉冰浮水@bilibili[/url]"
Tags: 哔哩哔哩
Type: 视频
Url: https://www.bilibili.com/video/BV1QMETeDEc7

```

**Comment by wdssmq** [comment]
```yml
Title: GitHub - wdssmq/blog-astro
Type: 代码
Url: https://github.com/wdssmq/blog-astro
Text: node:.post-intro
Source: "[url=https://github.com/wdssmq]wdssmq (沉冰浮水)@github[/url]"
Desc: 一个基于 Astro 的静态博客；
Tags: GitHub, astro, blog

```

**Comment by wdssmq** [comment]
```yml
Title: Z-BlogPHP - Grizzle - Z-Blog 应用中心
Desc: Grizzle - Z-Blog 应用中心
Image: https://app-cdn.zblogcn.com/files/phptheme/Grizzle/screenshot.png-screenshot
Source: "[url=https://app.zblogcn.com/?auth=6401c4a7-89cd-48f9-a68b-d6464d8c3bc8]沉冰浮水 - Z-Blog 应用中心[/url]"
Tags: Z-BlogPHP, Z-BlogPHP_插件
Type: 代码
Url: https://app.zblogcn.com/?id=649

```

**Comment by wdssmq** [comment]
```yml
Title: Z-BlogPHP - 这就是咸鱼吗？（仮） - Z-Blog 应用中心
Desc: 这就是咸鱼吗？（仮） - Z-Blog 应用中心
Image: https://app-cdn.zblogcn.com/files/phptheme/acgMora/screenshot.png-screenshot
Source: "[url=https://app.zblogcn.com/?auth=6401c4a7-89cd-48f9-a68b-d6464d8c3bc8]沉冰浮水 - Z-Blog 应用中心[/url]"
Tags: Z-BlogPHP, Z-BlogPHP_插件
Type: 代码
Url: https://app.zblogcn.com/?id=2235

```

**Comment by wdssmq** [comment]
```yml
Title: Z-BlogPHP - 「开发工具」Grunt - Z-Blog 应用中心
Desc: 「开发工具」Grunt - Z-Blog 应用中心
Image: https://app-cdn.zblogcn.com/files/phpplugin/mzGrunt/logo.png
Source: "[url=https://app.zblogcn.com/?auth=6401c4a7-89cd-48f9-a68b-d6464d8c3bc8]沉冰浮水 - Z-Blog 应用中心[/url]"
Tags: Z-BlogPHP, Z-BlogPHP_插件
Type: 代码
Url: https://app.zblogcn.com/?id=2110

```

**Comment by wdssmq** [comment]
```yml
Title: GitHub - wdssmq/php-nginx-dc
Desc: 用于部署多站点 PHP + Nginx 环境的 Docker Compose 配置，使用 webdevop…
Image: null
Source: "[url=https://github.com/wdssmq]wdssmq (沉冰浮水)@github[/url]"
Tags: GitHub
Type: 代码
Url: https://github.com/wdssmq/php-nginx-dc

```

**Comment by wdssmq** [comment]
```yaml
Title: 「游戏」《Deiland》丢失过很多次存档的「小王子」游戏
Desc: 所以为什么没录到声音；

存档在注册表里，重装系统也没想过备份，就一直没能通关；
Source: [url=https://space.bilibili.com/44744006]沉冰浮水@bilibili[/url]
Tags: 哔哩哔哩
Type: 视频
Url: https://www.bilibili.com/video/BV14z4y1i78J

```
